/* Local licensed-font bridge for NametagFlow. Font bytes stay on this device and are never uploaded. */
(function(root){
'use strict';
var BUILD='13.8.9', loaded={arial:null,swis:null}, sources={arial:'',swis:''}, restored=false, restoring=null;
var DB_NAME='NametagFlowLocalFonts',DB_VERSION=1,STORE='fonts';
function openDb(){return new Promise(function(resolve,reject){if(typeof indexedDB==='undefined')return resolve(null);var req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=function(){var db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'key'});};req.onsuccess=function(){resolve(req.result);};req.onerror=function(){reject(req.error||new Error('Penyimpanan font lokal tidak tersedia.'));};});}
async function storeFont(key,buffer,name){try{var db=await openDb();if(!db)return false;await new Promise(function(resolve,reject){var tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({key:key,buffer:buffer.slice(0),name:name||'',savedAt:new Date().toISOString()});tx.oncomplete=function(){resolve();};tx.onerror=function(){reject(tx.error);};});db.close();return true;}catch(e){return false;}}
async function storedRecords(){var db=await openDb();if(!db)return[];try{return await new Promise(function(resolve,reject){var tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).getAll();req.onsuccess=function(){resolve(req.result||[]);};req.onerror=function(){reject(req.error);};});}finally{db.close();}}
async function deleteStored(key){try{var db=await openDb();if(!db)return;await new Promise(function(resolve,reject){var tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(key);tx.oncomplete=function(){resolve();};tx.onerror=function(){reject(tx.error);};});db.close();}catch(e){}}
function u16(v,o){return v.getUint16(o,false);} function i16(v,o){return v.getInt16(o,false);} function u32(v,o){return v.getUint32(o,false);} function tag(v,o){return String.fromCharCode(v.getUint8(o),v.getUint8(o+1),v.getUint8(o+2),v.getUint8(o+3));}
function n(v){var x=Math.round(v*1000000)/1000000;return Object.is(x,-0)?0:x;}
function parseSfnt(buffer,label){
 var v=new DataView(buffer),magic=tag(v,0);if(magic==='ttcf')throw new Error(label+' terdeteksi sebagai koleksi TTC. Pilih file TTF face Regular-nya secara langsung.');
 var scalar=u32(v,0);if(scalar!==0x00010000&&magic!=='true')throw new Error(label+' bukan TrueType outline (.ttf) yang didukung. Gunakan file TTF Regular.');
 var num=u16(v,4),tables={};for(var i=0;i<num;i++){var o=12+i*16,t=tag(v,o);tables[t]={offset:u32(v,o+8),length:u32(v,o+12)};}
 ['head','maxp','hhea','hmtx','loca','glyf','cmap'].forEach(function(t){if(!tables[t])throw new Error(label+' tidak memiliki tabel TrueType '+t+'.');});
 var head=tables.head.offset,units=u16(v,head+18),locFmt=i16(v,head+50),numGlyphs=u16(v,tables.maxp.offset+4),numMetrics=u16(v,tables.hhea.offset+34),hmtx=tables.hmtx.offset,loca=tables.loca.offset,glyf=tables.glyf.offset;
 if(!units||numGlyphs<1)throw new Error(label+' memiliki metadata font yang tidak valid.');
 var advances=new Array(numGlyphs),last=0;for(i=0;i<numGlyphs;i++){if(i<numMetrics){last=u16(v,hmtx+i*4);advances[i]=last;}else advances[i]=last;}
 function glyphOffset(g){return loca+(locFmt===0?g*2:g*4);} function glyphPos(g){return glyf+(locFmt===0?u16(v,glyphOffset(g))*2:u32(v,glyphOffset(g)));}
 function cmapReader(){var base=tables.cmap.offset,count=u16(v,base+2),best=null,score=-1;for(var j=0;j<count;j++){var ro=base+4+j*8,p=u16(v,ro),e=u16(v,ro+2),so=base+u32(v,ro+4),fmt=u16(v,so),s=(fmt===12?20:fmt===4?10:0)+(p===3?5:p===0?4:0)+(e===10?3:e===1?2:0);if(s>score){best={o:so,f:fmt};score=s;}}if(!best||![4,12].includes(best.f))throw new Error(label+' tidak memiliki cmap Unicode yang didukung.');
  if(best.f===12){var groups=u32(v,best.o+12),go=best.o+16;return function(cp){var lo=0,hi=groups-1;while(lo<=hi){var m=(lo+hi)>>1,o=go+m*12,a=u32(v,o),b=u32(v,o+4);if(cp<a)hi=m-1;else if(cp>b)lo=m+1;else return u32(v,o+8)+(cp-a);}return 0;};}
  var segCount=u16(v,best.o+6)/2,endOff=best.o+14,startOff=endOff+2*segCount+2,deltaOff=startOff+2*segCount,rangeOff=deltaOff+2*segCount;return function(cp){for(var k=0;k<segCount;k++){var end=u16(v,endOff+2*k);if(cp>end)continue;var start=u16(v,startOff+2*k);if(cp<start)return 0;var delta=i16(v,deltaOff+2*k),range=u16(v,rangeOff+2*k);if(!range)return (cp+delta)&65535;var addr=rangeOff+2*k+range+2*(cp-start);if(addr+1>=v.byteLength)return 0;var gid=u16(v,addr);return gid?((gid+delta)&65535):0;}return 0;};
 }
 function readNames(){var t=tables.name;if(!t)return{};var base=t.offset,format=u16(v,base),count=u16(v,base+2),stringOff=u16(v,base+4),out={};for(var r=0;r<count;r++){var ro=base+6+r*12,platform=u16(v,ro),nameId=u16(v,ro+6),len=u16(v,ro+8),off=u16(v,ro+10),start=base+stringOff+off;if(start+len>v.byteLength)continue;var value='';if(platform===0||platform===3){for(var z=0;z+1<len;z+=2)value+=String.fromCharCode(u16(v,start+z));}else{for(var z2=0;z2<len;z2++)value+=String.fromCharCode(v.getUint8(start+z2));}if(value&&!out[nameId])out[nameId]=value;}return{family:out[1]||'',style:out[2]||'',fullName:out[4]||'',postscriptName:out[6]||'',format:format};}
 var names=readNames();
 var glyphIndex=cmapReader(),cache={};
 function simple(gid,pos,contours){var p=pos+10,ends=[],j;for(j=0;j<contours;j++){ends.push(u16(v,p));p+=2;}var points=ends[ends.length-1]+1,ins=u16(v,p);p+=2+ins;var flags=[],f;while(flags.length<points){f=v.getUint8(p++);flags.push(f);if(f&8){var rep=v.getUint8(p++);while(rep--)flags.push(f);}}var xs=[],ys=[],x=0,y=0;for(j=0;j<points;j++){f=flags[j];var dx=0;if(f&2){dx=v.getUint8(p++);if(!(f&16))dx=-dx;}else if(!(f&16)){dx=i16(v,p);p+=2;}x+=dx;xs.push(x);}for(j=0;j<points;j++){f=flags[j];var dy=0;if(f&4){dy=v.getUint8(p++);if(!(f&32))dy=-dy;}else if(!(f&32)){dy=i16(v,p);p+=2;}y+=dy;ys.push(y);}var all=[],start=0;for(j=0;j<contours;j++){var arr=[];for(var q=start;q<=ends[j];q++)arr.push({x:xs[q],y:ys[q],on:!!(flags[q]&1)});all.push(arr);start=ends[j]+1;}return all;}
 function transformContours(contours,a,b,c,d,dx,dy){return contours.map(function(co){return co.map(function(p){return{x:p.x*a+p.y*c+dx,y:p.x*b+p.y*d+dy,on:p.on};});});}
 function contours(gid,depth){if(depth>8)throw new Error(label+' memiliki glyph komposit terlalu dalam.');var pos=glyphPos(gid),next=glyphPos(gid+1);if(pos===next)return[];var nc=i16(v,pos);if(nc>=0)return simple(gid,pos,nc);var p=pos+10,out=[],more=true,flags=0;while(more){flags=u16(v,p);var comp=u16(v,p+2);p+=4;var arg1,arg2;if(flags&1){arg1=i16(v,p);arg2=i16(v,p+2);p+=4;}else{arg1=(v.getInt8(p));arg2=(v.getInt8(p+1));p+=2;}if(!(flags&2))throw new Error(label+' memakai komposit point-matching yang belum didukung. Gunakan file TTF standar face Regular.');var dx=arg1,dy=arg2,a=1,b=0,c=0,d=1;if(flags&8){a=d=i16(v,p)/16384;p+=2;}else if(flags&64){a=i16(v,p)/16384;d=i16(v,p+2)/16384;p+=4;}else if(flags&128){a=i16(v,p)/16384;b=i16(v,p+2)/16384;c=i16(v,p+4)/16384;d=i16(v,p+6)/16384;p+=8;}out=out.concat(transformContours(contours(comp,depth+1),a,b,c,d,dx,dy));more=!!(flags&32);}return out;}
 function contourPath(co){if(!co.length)return'';var first=co[0],last=co[co.length-1],start;if(first.on)start=first;else if(last.on)start=last;else start={x:(first.x+last.x)/2,y:(first.y+last.y)/2,on:true};var s='M'+n(start.x/units)+' '+n(-start.y/units),idx=first.on?1:0,limit=co.length+(first.on?0:1),arr=co.slice();if(!first.on)arr.push(first);for(var j=idx;j<limit;j++){var p=arr[j%arr.length];if(p.on){s+='L'+n(p.x/units)+' '+n(-p.y/units);}else{var nx=arr[(j+1)%arr.length];if(nx.on){s+='Q'+n(p.x/units)+' '+n(-p.y/units)+' '+n(nx.x/units)+' '+n(-nx.y/units);j++;}else{s+='Q'+n(p.x/units)+' '+n(-p.y/units)+' '+n((p.x+nx.x)/(2*units))+' '+n(-(p.y+nx.y)/(2*units));}}}return s+'Z';}
 function glyph(ch){if(cache[ch])return cache[ch];var cp=ch.codePointAt(0),gid=glyphIndex(cp);if(!gid&&cp!==32)throw new Error(label+' tidak memiliki karakter “'+ch+'”.');var pos=glyphPos(gid),next=glyphPos(Math.min(gid+1,numGlyphs)),d='',box=[0,0,0,0];if(pos!==next){var xMin=i16(v,pos+2),yMin=i16(v,pos+4),xMax=i16(v,pos+6),yMax=i16(v,pos+8);box=[n(xMin/units),n(-yMax/units),n(xMax/units),n(-yMin/units)];d=contours(gid,0).map(contourPath).join('');}return cache[ch]={d:d,a:n((advances[gid]||0)/units),b:box};}
 return{label:label,glyph:glyph,unitsPerEm:units,names:names};
}
function makeRuntime(parsed,key,chars){var glyphs={},set=new Set(Array.from(' '+(chars||'')));set.forEach(function(ch){glyphs[ch]=parsed.glyph(ch);});return{name:key==='arial'?'Arial Regular (lokal asli)':'Swis721 BT Regular (lokal asli)',version:BUILD,glyphs:glyphs,kernPairs:{},_parser:parsed,_local:true,_cssFamily:''};}
function extend(font,chars){if(!font||!font._parser)return font;Array.from(chars||'').forEach(function(ch){if(!font.glyphs[ch])font.glyphs[ch]=font._parser.glyph(ch);});return font;}
function extendKern(font,chars){if(!font||!font._cssFamily||typeof document==='undefined')return;var canvas=extendKern._canvas||(extendKern._canvas=document.createElement('canvas')),ctx=canvas.getContext('2d');if(!ctx)return;ctx.font='1000px "'+font._cssFamily+'"';if('fontKerning' in ctx)ctx.fontKerning='normal';var arr=Array.from(chars||'');for(var i=1;i<arr.length;i++){var pair=arr[i-1]+arr[i];if(Object.prototype.hasOwnProperty.call(font.kernPairs,pair))continue;var a=ctx.measureText(arr[i-1]).width,b=ctx.measureText(arr[i]).width,ab=ctx.measureText(pair).width;font.kernPairs[pair]=(ab-a-b)/1000;}}
function releaseFace(font){if(font&&font._face&&typeof document!=='undefined'&&document.fonts)document.fonts.delete(font._face);}
async function attachFace(font,buffer,key,chars){if(typeof FontFace==='undefined'||typeof document==='undefined'||!document.fonts)return font;var family='NF_'+(key==='arial'?'Arial':'Swis721')+'_'+Date.now()+'_'+Math.random().toString(36).slice(2);var face=new FontFace(family,buffer);await face.load();document.fonts.add(face);font._cssFamily=family;font._face=face;try{extendKern(font,chars);}catch(e){releaseFace(font);throw e;}return font;}
function status(){return{arial:!!loaded.arial,swis:!!loaded.swis,arialSource:sources.arial,swisSource:sources.swis,ready:!!loaded.arial&&!!loaded.swis};}
function classify(meta){
 var norm=function(v){return String(v||'').toLowerCase().replace(/[\s_-]+/g,'');},family=norm(meta.family),full=norm(meta.fullName),post=norm(meta.postscriptName),style=norm(meta.style),all=family+' '+full+' '+post+' '+style;
 if(/bold|italic|oblique|narrow|condensed|extended|black|light|demi|medium/.test(all))return'';
 if(style&&!['regular','normal','roman'].includes(style))return'';
 if(family){if(['arial','arialmt'].includes(family))return'arial';if(['swis721bt','swiss721bt'].includes(family))return'swis';return'';}
 if(['arial','arialregular','arialroman'].includes(full)||['arialmt','arialregular','arialroman'].includes(post))return'arial';
 if(['swis721bt','swis721btregular','swis721btroman','swiss721bt','swiss721btregular','swiss721btroman'].includes(full)||['swis721btroman','swis721btregular','swiss721btroman','swiss721btregular'].includes(post))return'swis';
 return'';
}
function validateFace(parsed,key){if(classify(parsed.names||{})!==key)throw new Error('File yang dipilih bukan '+(key==='arial'?'Arial Regular':'Swis721 BT Regular')+' standar. Pilih face Regular/Roman, bukan font pengganti atau varian lain.');return true;}
async function activateBuffer(key,buffer,name,chars,persist){if(key!=='arial'&&key!=='swis')throw new Error('Jenis font lokal tidak dikenal.');var label=key==='arial'?'Arial Regular':'Swis721 BT Regular',parsed=parseSfnt(buffer,label);validateFace(parsed,key);var candidate=makeRuntime(parsed,key,chars);await attachFace(candidate,buffer,key,chars);var saved=persist?await storeFont(key,buffer,name||'font lokal'):true;releaseFace(loaded[key]);loaded[key]=candidate;sources[key]=(name||'font lokal')+(persist?(saved?' · tersimpan lokal':' · hanya sesi ini (penyimpanan browser gagal)'):'');return loaded[key];}
async function restore(chars){if(restored)return status();if(restoring)return restoring;restoring=(async function(){try{var rows=await storedRecords();for(var i=0;i<rows.length;i++){var r=rows[i];if(r.key!=='arial'&&r.key!=='swis')continue;try{await activateBuffer(r.key,r.buffer,r.name,chars,false);sources[r.key]=(r.name||'font lokal')+' · tersimpan lokal';}catch(e){loaded[r.key]=null;sources[r.key]='';await deleteStored(r.key);}}}catch(e){}finally{restored=true;restoring=null;}return status();})();return restoring;}
async function fromFontData(fd,key,chars){var blob=await fd.blob(),buf=await blob.arrayBuffer(),name=(fd.fullName||fd.family||fd.postscriptName||'font lokal');await activateBuffer(key,buf,name,chars,true);return loaded[key];}
async function detect(chars){await restore(chars);if(status().ready)return status();if(typeof root.queryLocalFonts!=='function')return status();var list=await root.queryLocalFonts(),pick={};for(var i=0;i<list.length;i++){var k=classify(list[i]);if(k&&!pick[k])pick[k]=list[i];}if(!loaded.arial&&pick.arial)await fromFontData(pick.arial,'arial',chars);if(!loaded.swis&&pick.swis)await fromFontData(pick.swis,'swis',chars);return status();}
async function loadFile(key,file,chars){if(!file)throw new Error('Pilih file font terlebih dahulu.');if(file.size>20*1024*1024)throw new Error('File font terlalu besar.');var buf=await file.arrayBuffer();await activateBuffer(key,buf,file.name,chars,true);return status();}
async function clear(){releaseFace(loaded.arial);releaseFace(loaded.swis);loaded={arial:null,swis:null};sources={arial:'',swis:''};restored=true;await deleteStored('arial');await deleteStored('swis');return status();}
function charsFromOrders(rows){var s='LOGONIP. ';(rows||[]).forEach(function(o){s+=String(o.name||'')+String(o.nip||'');});return s;}
function prepare(rows){var chars=charsFromOrders(rows);extend(loaded.arial,chars);extend(loaded.swis,chars);extendKern(loaded.arial,chars);extendKern(loaded.swis,chars);return status();}
function get(key,chars){var f=loaded[key];if(!f)return null;extend(f,chars);extendKern(f,chars);return f;}
function requireReady(rows){prepare(rows);if(!loaded.arial||!loaded.swis)throw new Error('Font Corel asli belum siap. Hubungkan Arial Regular dan Swis721 BT Regular dari PC sebelum membuat PDF.');return true;}
root.NFLocalFonts={BUILD:BUILD,status:status,restore:restore,detect:detect,loadFile:loadFile,clear:clear,prepare:prepare,get:get,requireReady:requireReady,charsFromOrders:charsFromOrders,_parseForTest:parseSfnt};
if(typeof module!=='undefined')module.exports=root.NFLocalFonts;
})(globalThis);
