'use strict';
// Run with Node 18+ (no installation, no network, no production data).
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');global.crypto??=crypto.webcrypto;
const C=require(root+'/core.js');require(root+'/print-font.js');const P=require(root+'/print-engine.js');global.PDFLib=require(root+'/vendor/pdf-lib.min.js');
const clone=structuredClone,models=['Lis + Nama','Lis + Nama + NIP','Lis + Logo + Nama','Lis + Logo + Nama + NIP','Lis + Logo + Nama + Line + NIP','Polos + Nama','Polos + Nama + NIP','Polos + Logo + Nama','Polos + Logo + Nama + NIP','Polos + Logo + Nama + Line + NIP'].map((s,i)=>`Model ${i+1} (${s})`);
const order=(id='NT-TEST')=>({id,revision:'rev0',name:'SUPRIYADI',nip:'00198912022024210023',model:models[0],mp:'000123456789123456789',hook:'Magnet',logo:'',resi:'',sku:'',notes:'',currentStep:6,printCount:1,isReject:false,rejectReason:'',createdAt:'2026-09-29T05:00:00.000Z',productionDate:''});
const snapshot=rows=>({orders:rows,archives:[],recycle:[],settings:{models,hooks:['Magnet','Peniti'],skus:[]}});
const state=rows=>({snapshot:snapshot(rows),pending:[]});
const upsert=o=>({kind:'upsert',id:o.id,expectedRevision:o.revision,opId:C.uid(),data:C.fields(o)});
const ack=(op,o)=>({committed:true,opId:op.opId,id:op.id,kind:op.kind,order:{...o,revision:C.uid('rev-')}});
const cases=[];function test(name,fn){cases.push([name,fn]);}
function printing(){const o={...order(),currentStep:1},j=P.createJob([o]);j.downloadedAt=j.createdAt;const s={...state([o]),printJobs:[j]};return{o,j,s};}
function backend(){
 const tables=new Map();let crashFlush=0,flushes=0;
 function sheet(name,width){
  let columns=width;const data=[Array(width).fill('HEADER')];const s={data,getLastRow:()=>data.length,getMaxColumns:()=>columns,insertColumnsAfter:(_at,n)=>{columns+=n;},setFrozenRows:()=>{},
   getRange:(row,col,nr=1,nc=1)=>({getValues:()=>Array.from({length:nr},(_,i)=>Array.from({length:nc},(_,j)=>clone(data[row+i-1]?.[col+j-1]??''))),getValue:()=>clone(data[row-1]?.[col-1]??''),getDisplayValues:()=>Array.from({length:nr},(_,i)=>Array.from({length:nc},(_,j)=>String(data[row+i-1]?.[col+j-1]??''))),setValue:v=>{data[row-1]??=[];data[row-1][col-1]=clone(v);},setValues:rows=>{assert.equal(rows.length,nr);for(const r of rows)assert.equal(r.length,nc,'Sheets range width must match values');rows.forEach((r,i)=>{data[row+i-1]??=[];r.forEach((v,j)=>data[row+i-1][col+j-1]=clone(v));});}}),
   getRangeList:()=>({setNumberFormat:()=>{}}),appendRow:r=>data.push(clone(r)),deleteRow:r=>data.splice(r-1,1)};tables.set(name,s);return s;
 }
 sheet('Antrean Produksi',16);sheet('Arsip Produksi',14);sheet('_NF_Operations',7);sheet('_NF_Recycle',6);sheet('Log Perubahan',8);
 const settings=sheet('Pengaturan',12);models.forEach((m,i)=>{const r=Array(12).fill('');r[0]=m;r[2]=i===0?'Magnet':i===1?'Peniti':'';settings.data.push(r);});
 const ctx=vm.createContext({console,Date,Map,Set,Utilities:{getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_alg,v)=>[...crypto.createHash('sha256').update(v).digest()],formatDate:(v)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(v)},SpreadsheetApp:{openById:()=>({getSheetByName:n=>tables.get(n)||null}),flush:()=>{flushes++;if(crashFlush===flushes){crashFlush=0;throw new Error('TEST_INTERRUPTION');}}}});
 vm.runInContext(fs.readFileSync(root+'/backend/Code.gs','utf8'),ctx);
 const active=tables.get('Antrean Produksi'),archives=tables.get('Arsip Produksi');
 function seed(o=order()){const row=[o.id,o.name,o.nip,o.model,o.hook,o.logo||'-',o.mp,o.resi,o.sku,o.printCount,o.currentStep,o.isReject?'YA':'TIDAK',o.rejectReason,new Date(o.createdAt),new Date(o.createdAt),o.notes];if(o.productionDate)row.push(o.productionDate);active.data.push(row);return ctx.nfOrder_(row);}
 function seedArchive(o=order()){const row=[new Date('2026-09-29T10:00:00Z'),o.id,o.name,o.nip,o.model,o.hook,o.logo||'-',o.mp,o.resi,o.sku,o.printCount,'Selesai Transaksi',new Date(o.createdAt),o.notes];archives.data.push(row);return ctx.nfArchive_(row);}
 function mutate(op,role='operator'){return ctx.nfMutate_(op,role,'TESTER');}
 function batch(ops,role='operator'){return ctx.nfMutateBatch_(ops.map(operation=>({operation,operator:'TESTER'})),role);}
 function reprint(o){return{kind:'reprint',id:o.id,opId:C.uid(),expectedRevision:o.revision,reason:'Kotor / bernoda',productionDate:'2026-09-30',data:C.fields(o)};}
 return{ctx,tables,active,archives,seed,seedArchive,mutate,batch,reprint,crashAfter:n=>{crashFlush=flushes+n;}};
}

test('Legacy pending form saved after acknowledgment becomes ready',()=>{const o=order(),s=state([o]);C.queueOperations(s,[upsert(o)],'Test');const first=s.pending[0].operation,captured=C.overlay(s.snapshot,s.pending)[0];C.applyAcknowledgment(s,first,ack(first,{...o,...first.data}));C.queueOperations(s,[{...upsert(captured),data:{...C.fields(captured),name:'UPDATED'}}],'Test');assert.equal(C.readyOperations(s.pending).length,1);assert.equal(s.pending[0].operation.expectedRevision,s.snapshot.orders[0].revision);});
test('Unknown orphan pending revision becomes inspectable instead of waiting',()=>{const o=order(),s=state([o]);C.queueOperations(s,[{...upsert(o),expectedRevision:'pending:op_missing123'}],'Test');assert.equal(s.pending[0].status,'blocked');assert.equal(s.pending[0].code,'STALE_DRAFT');});
test('Changed remote version is not silently overwritten during dependency repair',()=>{const o=order(),s=state([o]);s.operationReceipts={op_old:{id:o.id,revision:'prior'}};C.queueOperations(s,[{...upsert(o),expectedRevision:'pending:op_old'}],'Test');assert.equal(s.pending[0].status,'blocked');});
test('Queued dependencies release after predecessor acknowledgment',()=>{const o=order(),s=state([o]);C.queueOperations(s,[upsert(o)],'A');const first=s.pending[0].operation;s.pending[0].attempted=true;C.queueOperations(s,[{...upsert(o),expectedRevision:'pending:'+first.opId}],'B');assert.equal(C.readyOperations(s.pending).length,1);C.applyAcknowledgment(s,first,ack(first,o));assert.equal(C.readyOperations(s.pending).length,1);});
test('Unsaved edits to the same draft still coalesce',()=>{const o=order(),s=state([o]);C.queueOperations(s,[upsert(o)],'A');const first=s.pending[0].operation;C.queueOperations(s,[{...upsert(o),expectedRevision:'pending:'+first.opId,data:{...C.fields(o),name:'NEW'}}],'A');assert.equal(s.pending.length,1);assert.equal(s.pending[0].operation.data.name,'NEW');});
test('All 10 models retain 55/73 mm name limits',()=>{for(let i=0;i<10;i++){const o={...order(),model:models[i]},a=P.artwork(o,{}, {[P.logoKey(o)]:{omit:true}});assert(a.nameWidth<=([2,3,4,7,8,9].includes(i)?55:73));}});
test('Corel layout fits 29 tags and paginates the 30th; PDF keeps actual paper size',async()=>{const rows=Array.from({length:30},(_,i)=>order('NT-'+i)),layout=P.plan(rows);assert.equal(layout.grid.capacity,29);assert(Math.abs(layout.grid.left-34.175)<.001);assert(Math.abs(layout.grid.top-11.85)<.001);assert(Math.abs(layout.grid.sideLeft-13.375)<.001);assert.equal(layout.pages[0].length,29);assert.equal(layout.pages[0].filter(x=>x.rotation===90).length,3);const doc=await PDFLib.PDFDocument.load(await P.pdf(P.createJob(rows)));assert.equal(doc.getPageCount(),2);assert(Math.abs(doc.getPage(0).getWidth()*25.4/72-210)<.001);assert(Math.abs(doc.getPage(0).getHeight()*25.4/72-290)<.001);});

test('Reference typography uses Arial-compatible regular metrics and Corel short-name tracking',()=>{const sup=P.artwork({...order(),name:'SUPRIYADI'}),short=P.artwork({...order(),name:'SAHREL',model:models[5]}),spaced=P.artwork({...order(),name:'S A H R E L',model:models[5]});assert.equal(sup.font,'Arial-compatible Regular (Arimo)');assert(sup.nameWidth>51&&sup.nameWidth<53);assert(short.nameWidth>51&&short.nameWidth<54);assert.equal(short.nameSpacing,2.734);assert.equal(spaced.nameSpacing,0);});
test('Corel source font sizes are converted to exact cap-height equivalents',()=>{assert(Math.abs(P.DEFAULTS.nameHeight-6.771)<.0001);assert(Math.abs(P.DEFAULTS.nameNipHeight-5.294)<.0001);assert(Math.abs(P.DEFAULTS.nipHeight-3.29)<.0001);assert(Math.abs(P.DEFAULTS.shortSpacing-2.734)<.0001);});
test('Reference border, NIP and divider strokes match measured CDR geometry',()=>{const bordered=P.artwork(order()),outer=bordered.shapes[0],inner=bordered.shapes[1];assert.equal(outer.line,.1);assert.equal(inner.line,.2);for(const i of [1,3,4,6,8,9]){const o={...order(),model:models[i],logo:'DEMO'},a=P.artwork(o,{}, {[P.logoKey(o)]:{omit:true}}),lines=a.shapes.filter(x=>x.type==='line');assert(lines.some(x=>x.line===.75));}});
test('Reference logo boxes are smaller and remain inside the reserved logo column',()=>{for(const i of [2,3,4,7,8,9]){const o={...order(),model:models[i],logo:'DEMO'},a=P.artwork(o,{}, {[P.logoKey(o)]:fixtureLogo()}),image=a.shapes.find(x=>x.type==='image');assert(image.w<=12.4+.001);assert(image.h<=14.2+.001);assert(image.x+image.w<20);}});
test('Legacy v13.6 jobs retain the old font and geometry when redownloaded',()=>{const old=P.LEGACY_DEFAULTS,o={...order(),model:models[1]},a=P.artwork(o,old,{},false,'13.6.0');assert.equal(a.font,'DejaVu Sans Bold');assert.equal(a.shapes.find(x=>x.type==='line').line,.3);assert.equal(P.plan(Array.from({length:25},(_,i)=>order('L-'+i)),old,{},false,'13.6.0').grid.capacity,24);});
test('Saved v13.7 jobs retain Arimo Bold and v13.7 border geometry',()=>{const o={...order(),model:models[0]},a=P.artwork(o,P.V13_7_DEFAULTS,{},false,'13.7.0');assert.equal(a.font,'Arial-compatible Bold (Arimo)');assert.equal(a.shapes[0].line,.35);assert.equal(a.nameSpacing,0);});
test('Old saved print settings migrate to the v13.8 Corel reference defaults for new jobs',()=>{const oldSaved={...P.V13_7_DEFAULTS};delete oldSaved.designVersion;const migrated=P.currentSettings(oldSaved);assert.equal(migrated.layoutMode,'corel29');assert.equal(migrated.condense,1);assert.equal(migrated.shortSpacing,2.734);assert.equal(migrated.nameHeight,6.771);assert.equal(migrated.nameNipHeight,5.294);assert.equal(migrated.nipHeight,3.29);assert.equal(migrated.designVersion,'13.8.2');});
test('Missing logo and unsupported font glyph block production PDF',()=>{assert.throws(()=>P.createJob([{...order(),model:models[2]}]),/belum diunggah/);assert.throws(()=>P.artwork({...order(),name:'测试'}),/belum didukung/);});
test('Gemini prompt prioritizes newest chat name, capitalization exceptions and Model 1 default',()=>{const prompt=C.bulkPrompt(snapshot([]).settings);assert.match(prompt,/nama di Catatan Pesanan.*chat.*lebih baru/i);assert.match(prompt,/huruf kecil semua.*HURUF KAPITAL/i);assert.match(prompt,/jangan diubah/i);assert.match(prompt,/HANYA mengirim nama.*Model 1/i);assert.match(prompt,/Model 10 = POLOS/i);assert(prompt.includes('NP\tNama\tNIP\tModel\tPengait\tLogo\tResi\tSKU\tCatatan'));});
test('Optional SKU, leading zero identifiers and identical names survive import',()=>{const r=C.parseBulk('NP\tNama\tNIP\tModel\tPengait\tSKU\n0000123456789123456789\tADI\t00198912022024210023\t2\tM\tNEW\n0000123456789123456789\tADI\t00198912022024210023\t2\tM\tNEW',snapshot([]));assert.equal(r.rows.length,2);assert.equal(r.duplicateCount,1);assert.equal(r.rows[0].errors.length,0);assert.equal(r.rows[0].data.nip,'00198912022024210023');assert.equal(r.rows[0].data.mp,'0000123456789123456789');assert.equal(r.rows[0].data.sku,'NEW');});
test('Scientific NIP is rejected by import, order validation and print engine',()=>{for(const nip of ['1.98912E+17','1,98912e17','NIP. 1.98912e+17']){const o={...order(),nip};assert.throws(()=>C.validateIdentifiers(o),/notasi ilmiah/);assert.throws(()=>P.artwork(o),/notasi ilmiah/);const r=C.parseBulk('NP\tNama\tNIP\tModel\tPengait\n123\tADI\t'+nip+'\t2\tM',snapshot([]));assert(r.rows[0].errors.some(e=>e.includes('notasi ilmiah')));}});
test('Backend independently rejects scientific NIP',()=>{const b=backend(),o={...order(),nip:'1.98912E+17',revision:null};assert.throws(()=>b.mutate(upsert(o)),/notasi ilmiah/);});
test('Finish print is idempotent and clears reprint flag after successful print',()=>{const {o,j,s}=printing();o.isReject=true;s.snapshot.orders[0].isReject=true;P.finishJob(s,j.id,'Test');P.finishJob(s,j.id,'Test');assert.equal(s.pending.length,1);assert.equal(s.pending[0].operation.data.currentStep,2);assert.equal(s.pending[0].operation.data.isReject,false);assert.equal(s.pending[0].operation.data.printCount,1);});
test('Old PDF cannot complete a later print cycle',()=>{const {j,s}=printing();s.snapshot.orders[0].printCount=2;assert.throws(()=>P.finishJob(s,j.id,'Test'),/nomor cetakan/);assert.equal(s.pending.length,0);});
test('Changed printed name blocks completion',()=>{const {j,s}=printing();s.snapshot.orders[0].name='DIFFERENT';assert.throws(()=>P.finishJob(s,j.id,'Test'),/berubah/);});
test('Print status follows a rebased operation and its acknowledgment',()=>{const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const old=s.pending[0].operation,replacement={...old,opId:C.uid()};NFPrint.relinkOperation(s,old.opId,replacement.opId);s.pending=[{operation:replacement,status:'queued'}];assert.match(P.jobStatus(j,s),/menunggu 1/);C.applyAcknowledgment(s,replacement,ack(replacement,{...o,...replacement.data}));assert.equal(P.jobStatus(j,s),'Cetak dikonfirmasi');});
test('Repeated rebases and exported print backups preserve operation linkage',()=>{const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const old=s.pending[0].operation,a=C.uid(),b=C.uid();P.relinkOperation(s,old.opId,a);P.relinkOperation(s,a,b);const op={...old,opId:b};s.pending=[{operation:op,status:'queued'}];const saved={...j,moves:P.exportMoves(j,s)};assert.equal(saved.moves[0].activeOpId,b);C.applyAcknowledgment(s,op,ack(op,{...o,...op.data}));assert.equal(P.jobStatus(j,s),'Cetak dikonfirmasi');assert.equal(P.jobStatus(saved,{pending:[],operationReceipts:s.operationReceipts}),'Cetak dikonfirmasi');});
test('Discarded print move is clearly cancelled without a phantom pending item',()=>{const {j,s}=printing();P.finishJob(s,j.id,'Test');P.cancelOperations(s,s.pending.map(p=>p.operation.opId));s.pending=[];assert.equal(P.jobStatus(j,s),'Cetak dikonfirmasi · perpindahan dibatalkan');});
test('Print conflict resolution cannot overwrite a new cycle or move a later stage backwards',()=>{const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const op=s.pending[0].operation;assert.throws(()=>P.rebaseData(s,op,{...o,printCount:2}),/nomor cetakan/);const d=P.rebaseData(s,op,{...o,currentStep:4,resi:'LATEST'});assert.equal(d.currentStep,4);assert.equal(d.resi,'LATEST');});
test('Production day uses original date before scheduling and new date afterwards',()=>{assert.equal(C.productionDay(order()),'2026-09-29');assert.equal(C.productionDay({...order(),productionDate:'2026-09-30'}),'2026-09-30');});
test('Pending reprint overlay appears today without changing original date or ID',()=>{const o=order(),s=state([o]);C.queueOperations(s,[{kind:'reprint',id:o.id,expectedRevision:o.revision,productionDate:'2026-09-30',reason:'Kotor',data:C.fields(o)}],'Test');const shown=C.overlay(s.snapshot,s.pending);assert.equal(shown.length,1);assert.equal(shown[0].id,o.id);assert.equal(shown[0].createdAt,o.createdAt);assert.equal(shown[0].printCount,2);assert.equal(shown[0].currentStep,1);assert.equal(C.productionDay(shown[0]),'2026-09-30');});
test('Schema upgrade appends metadata and preserves legacy 16-column revisions',()=>{const b=backend(),o=b.seed(),before=clone(b.active.data[1]),oldHash=b.ctx.nfDigest_(before);b.ctx.nfSnapshot_('operator');assert.equal(b.active.data[0][16],'Tanggal Produksi');assert.deepEqual(b.active.data[1],before);assert.equal(b.ctx.nfRevision_([...before,'']),oldHash);const res=b.mutate({...upsert(o),data:{...C.fields(o),name:'UPDATED'}});assert.equal(res.order.name,'UPDATED');});
test('Schema refuses to overwrite a custom Q header or existing Q contents',()=>{for(const customHeader of [true,false]){const b=backend();b.seed();b.active.insertColumnsAfter(16,1);if(customHeader)b.active.data[0][16]='CUSTOM';else b.active.data[1][16]='KEEP';assert.throws(()=>b.ctx.nfSnapshot_('operator'),/Kolom Q/);assert.equal(customHeader?b.active.data[0][16]:b.active.data[1][16],customHeader?'CUSTOM':'KEEP');}});
test('Active reprint keeps ID and original date, increments count once, schedules today',()=>{const b=backend(),o=b.seed(),op=b.reprint(o),result=b.mutate(op);assert.equal(result.order.id,o.id);assert.equal(result.order.createdAt,o.createdAt);assert.equal(result.order.printCount,2);assert.equal(result.order.currentStep,1);assert.equal(result.order.productionDate,'2026-09-30');assert.equal(result.order.isReject,true);assert.equal(result.order.rejectReason,'Kotor / bernoda');assert.equal(b.active.data.length,2);const retry=b.mutate(op);assert.equal(retry.order.printCount,2);assert.equal(b.active.data.length,2);});
test('A second request using the old revision cannot double-increment reprint',()=>{const b=backend(),o=b.seed();b.mutate(b.reprint(o));assert.throws(()=>b.mutate(b.reprint(o)),/Data pusat telah berubah/);assert.equal(b.ctx.nfSnapshot_('operator').orders[0].printCount,2);});
test('Reprint requires a reason and valid date and enforces maximum count',()=>{const b=backend(),o=b.seed();assert.throws(()=>b.mutate({...b.reprint(o),reason:''}),/Alasan/);assert.throws(()=>b.mutate({...b.reprint(o),productionDate:'2026-02-30'}),/Tanggal produksi/);const b2=backend(),o2=b2.seed({...order(),printCount:999});assert.throws(()=>b2.mutate(b2.reprint(o2)),/999/);});
test('Editing and advancing a reprint preserves its production date and original date',()=>{const b=backend(),o=b.seed(),r=b.mutate(b.reprint(o)).order;const result=b.mutate({...upsert(r),data:{...C.fields(r),name:'UPDATED',productionDate:'2027-01-01',currentStep:2,isReject:false}}).order;assert.equal(result.productionDate,'2026-09-30');assert.equal(result.createdAt,o.createdAt);assert.equal(result.printCount,2);});
test('Owner can reprint from archive without duplicating active or archived orders',()=>{const b=backend(),o=b.seedArchive();const op=b.reprint(o);assert.throws(()=>b.mutate(op,'operator'),/pemilik/);const r=b.mutate(op,'admin').order;assert.equal(r.id,o.id);assert.equal(r.createdAt,o.createdAt);assert.equal(r.printCount,2);assert.equal(r.currentStep,1);assert.equal(b.active.data.length,2);assert.equal(b.archives.data.length,1);assert.equal(b.mutate(op,'admin').order.printCount,2);});
test('Reprint acknowledgment removes source archive in the frontend',()=>{const o=order(),s=state([]);s.snapshot.archives=[{...o,archiveStatus:'Selesai Transaksi'}];const op={...upsert(o),kind:'reprint'};s.pending=[{operation:op,status:'queued'}];C.applyAcknowledgment(s,op,ack(op,{...o,currentStep:1,printCount:2,productionDate:'2026-09-30'}));assert.equal(s.snapshot.archives.length,0);assert.equal(s.snapshot.orders.length,1);});
test('Interrupted reprint resumes safely at every durable phase',()=>{for(const phase of [1,2,3]){const b=backend(),o=b.seed(),op=b.reprint(o);b.crashAfter(phase);assert.throws(()=>b.mutate(op),/TEST_INTERRUPTION/);const r=b.mutate(op);assert.equal(r.order.printCount,2);assert.equal(b.active.data.length,2);assert.equal(r.order.productionDate,'2026-09-30');}});
test('Interrupted archive reprint resumes safely without losing the order',()=>{for(const phase of [1,2,3,4]){const b=backend(),o=b.seedArchive(),op=b.reprint(o);b.crashAfter(phase);assert.throws(()=>b.mutate(op,'admin'),/TEST_INTERRUPTION/);const r=b.mutate(op,'admin');assert.equal(r.order.printCount,2);assert.equal(b.active.data.length,2);assert.equal(b.archives.data.length,1);}});
test('Pending journal reserves tracking number and blocks a different NP',()=>{const b=backend(),a={...upsert({...order('NT-A'),mp:'NP-A',resi:'TRACKING',revision:null})},other={...upsert({...order('NT-B'),mp:'NP-B',resi:'TRACKING',revision:null})};b.crashAfter(1);assert.throws(()=>b.batch([a]),/TEST_INTERRUPTION/);const rejected=b.batch([other]);assert.equal(rejected.results[0].ok,false);assert.equal(rejected.results[0].code,'IDENTITY_CONFLICT');assert.equal(b.batch([a]).results[0].ok,true);assert.equal(b.active.data.length,2);});
test('Recovery rechecks tracking identity even after an external Sheet edit',()=>{const b=backend(),a=upsert({...order('NT-A'),mp:'NP-A',resi:'TRACKING',revision:null});b.crashAfter(1);assert.throws(()=>b.batch([a]),/TEST_INTERRUPTION/);b.seed({...order('NT-B'),mp:'NP-B',resi:'TRACKING'});const result=b.batch([a]);assert.equal(result.results[0].ok,false);assert.equal(result.results[0].code,'IDENTITY_CONFLICT');assert.equal(b.active.data.length,2);});
test('25-item fast batch remains idempotent with the new column',()=>{const b=backend(),ops=Array.from({length:25},(_,i)=>upsert({...order('NT-'+i),mp:'NP-'+i,revision:null}));const res=b.batch(ops);assert.equal(res.results.filter(r=>r.ok).length,25);assert.equal(b.active.data.length,26);assert.equal(b.batch(ops).results.filter(r=>r.ok).length,25);assert.equal(b.active.data.length,26);});
test('Legacy 16-column PENDING operation recovers after upgrade',()=>{const b=backend(),o=b.seed(),op=upsert(o),before=clone(b.active.data[1]),after=clone(before);after[1]='LEGACY UPDATE';after[13]=new Date('2026-09-30T02:00:00Z');const plan={opId:op.opId,id:op.id,kind:'upsert',actor:'Test',time:'2026-09-30T02:00:00Z',before,after};b.tables.get('_NF_Operations').data.push([op.opId,b.ctx.nfDigest_(op),'PENDING',JSON.stringify(plan),'',new Date(),'Test']);const r=b.mutate(op);assert.equal(r.order.name,'LEGACY UPDATE');assert.equal(b.active.data[1].length,18);});
test('Nonadjacent batch edits preserve intervening rows and original dates',()=>{const b=backend(),rows=[b.seed(order('NT-1')),b.seed(order('NT-2')),b.seed(order('NT-3'))],middle=clone(b.active.data[2]);const ops=[rows[0],rows[2]].map(o=>({...upsert(o),data:{...C.fields(o),currentStep:7}}));assert.equal(b.batch(ops).results.filter(r=>r.ok).length,2);assert.deepEqual(b.active.data[2],middle);});


function appHarness(rows,role='operator'){
 const elements=new Map();
 function parse(html){for(const match of html.matchAll(/<(\w+)\b([^>]*\bid="([^"]+)"[^>]*)>/g)){const el=element(match[3]);const value=match[2].match(/\bvalue="([^"]*)"/);if(value)el.value=value[1];if(match[1]==='select'){const rest=html.slice(match.index+match[0].length);const first=rest.match(/<option(?:\s[^>]*)?>([^<]*)<\/option>/);if(first)el.value=first[1];}}}
 function element(id){if(elements.has(id))return elements.get(id);let html='';const e={id,value:'',textContent:'',disabled:false,open:false,className:'',dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll:()=>[],showModal(){this.open=true;},close(){this.open=false;},get innerHTML(){return html;},set innerHTML(v){html=v;parse(v);}};elements.set(id,e);return e;}
 parse(fs.readFileSync(root+'/index.html','utf8'));
 const document={getElementById:id=>elements.get(id)||null,documentElement:{style:{setProperty(){}}},body:{classList:{toggle(){}}},querySelectorAll:()=>[],hidden:false};
 const ctx=vm.createContext({console,NFCore:C,NFPrint:P,NFPrintUI:{init(){},cancel(){}},document,localStorage:{getItem:()=>null,setItem(){}},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},navigator:{onLine:true},indexedDB:{open:()=>({})},setInterval:()=>0,setTimeout:()=>0,clearTimeout(){},confirm:()=>true,FormData:class{},URL,Blob,Date});
 ctx.window=ctx;ctx.addEventListener=()=>{};ctx.seed=clone(rows);ctx.seedRole=role;ctx.settings=snapshot([]).settings;
 vm.runInContext(fs.readFileSync(root+'/app.js','utf8'),ctx);
 vm.runInContext("S={snapshot:{orders:seed,archives:[],recycle:[],role:seedRole,settings,capabilities:{reprint:true,printCycle:true}},pending:[]};token='TEST';operator='TEST';render=()=>{};sync=()=>{};editState=async fn=>{fn(S);return S;};",ctx);
 return{ctx,e:id=>elements.get(id),run:code=>vm.runInContext(code,ctx),getState:()=>vm.runInContext('S',ctx)};
}
test('Actual reprint form enqueues once on double-submit and opens today filter',async()=>{const h=appHarness([order()]);h.run("reprintModal(['NT-TEST'])");assert(h.e('reprintForm'));const submit=()=>h.e('reprintForm').onsubmit({preventDefault(){}});await Promise.all([submit(),submit()]);const s=h.getState();assert.equal(s.pending.length,1);assert.equal(s.pending[0].operation.kind,'reprint');assert.equal(s.pending[0].operation.data.createdAt,order().createdAt);assert.equal(s.pending[0].operation.productionDate,h.run('today()'));assert.equal(h.e('dateFilter').value,h.run('today()'));assert.equal(h.run('page'),'active');});
test('Actual reprint form refuses changed data and pending orders',async()=>{const h=appHarness([order()]);h.run("reprintModal(['NT-TEST']);S.snapshot.orders[0].revision='changed'");await h.e('reprintForm').onsubmit({preventDefault(){}});assert.equal(h.getState().pending.length,0);assert.match(h.e('reprintError').textContent,/berubah/);const h2=appHarness([order()]);h2.run("S.pending=[{operation:{kind:'upsert',id:'NT-TEST',opId:'op_test123',data:NFCore.fields(S.snapshot.orders[0])},status:'queued'}];reprintModal(['NT-TEST'])");assert.equal(h2.e('reprintForm'),undefined);assert.match(h2.e('toast').textContent,/antrean simpan/);});
test('Actual archive reprint UI respects owner permission',()=>{const h=appHarness([]);h.ctx.archived={...order(),archiveStatus:'Selesai Transaksi'};h.run("S.snapshot.archives=[archived];reprintModal(['NT-TEST'])");assert.equal(h.e('reprintForm'),undefined);assert.match(h.e('toast').textContent,/pemilik/);const owner=appHarness([],'admin');owner.ctx.archived={...order(),archiveStatus:'Selesai Transaksi'};owner.run("S.snapshot.archives=[archived];reprintModal(['NT-TEST'])");assert(owner.e('reprintForm'));});
test('v13.8.2 print-cycle-only blocked upserts are safely requeued for the fixed backend',()=>{const h=appHarness([order()]);h.run("S.pending=[{operation:{kind:'upsert',id:'NT-TEST',opId:'op_test123',expectedRevision:'rev0',data:NFCore.fields(S.snapshot.orders[0])},status:'blocked',code:'PRINT_CYCLE_CHANGED',error:'old'}];repairPrintCycleBlocks(S)");const p=h.getState().pending[0];assert.equal(p.status,'queued');assert.equal(p.code,undefined);assert.equal(p.error,'');});

const fixtureLogo=(name='logo-demo.png')=>({data:'data:image/'+(name.endsWith('jpg')?'jpeg':'png')+';base64,'+fs.readFileSync(root+'/tests/fixtures/'+name).toString('base64'),width:name.includes('wide')?640:name.includes('lowres')?24:320,height:name.includes('wide')?240:name.includes('lowres')?24:320});
test('Print count is server-owned and cannot be reduced or raised through single or batch edits',()=>{for(const batch of [false,true]){for(const count of [1,3]){const b=backend(),o=b.mutate(b.reprint(b.seed())).order,op={...upsert(o),data:{...C.fields(o),printCount:count}};const saved=batch?b.batch([op]).results[0].data.order:b.mutate(op).order;assert.equal(saved.printCount,2);} }});
test('Server creates immutable cycles and ordinary edits adopt current server cycle metadata',()=>{for(const staleMode of ['missing','old']){const b=backend(),o=b.mutate(upsert({...order(),revision:null})).order;assert.match(o.printCycleId,/^PC-/);const updated=b.mutate({...upsert(o),data:{...C.fields(o),name:'ADI'}}).order;assert.equal(updated.printCycleId,o.printCycleId);const next=b.mutate(b.reprint(updated)).order;assert.notEqual(next.printCycleId,o.printCycleId);const printCycleId=staleMode==='missing'?'':o.printCycleId,saved=b.mutate({...upsert(next),data:{...C.fields(next),printCycleId,currentStep:2}}).order;assert.equal(saved.printCycleId,next.printCycleId);assert.equal(saved.printCount,next.printCount);}});
test('Immutable cycle rejects an old PDF even if Sheet print count was changed back',()=>{const b=backend(),o=b.seed({...order(),currentStep:1}),j=P.createJob([o]);j.downloadedAt=j.createdAt;b.mutate(b.reprint(o));b.active.data[1][9]=1;const live=b.ctx.nfSnapshot_('operator').orders[0];assert.throws(()=>P.finishJob({...state([live]),printJobs:[j]},j.id,'Test'),/nomor cetakan/);});
test('Backend checks print artwork signature independently of client receipts',()=>{const b=backend(),o=b.seed({...order(),currentStep:1}),j=P.createJob([o]),s={...state([o]),printJobs:[j]};j.downloadedAt=j.createdAt;P.finishJob(s,j.id,'Test');const print=s.pending[0].operation,changed=b.mutate({...upsert(o),data:{...C.fields(o),name:'NEW NAME'}}).order;assert.throws(()=>b.mutate({...print,expectedRevision:changed.revision}),e=>e.code==='PRINT_CYCLE_CHANGED');});
test('A dependent draft adopts only its confirmed creation cycle',()=>{const b=backend(),draft={...order(),revision:null},s=state([]);C.queueOperations(s,[upsert(draft)],'Test');const first=s.pending[0].operation,shown=C.overlay(s.snapshot,s.pending)[0];s.pending[0].attempted=true;C.queueOperations(s,[{...upsert(shown),data:{...C.fields(shown),name:'EDIT AFTER CREATE'}}],'Test');const result=b.mutate(first);C.applyAcknowledgment(s,first,result);assert.equal(s.pending[0].operation.data.printCycleId,result.order.printCycleId);assert.equal(b.mutate(s.pending[0].operation).order.name,'EDIT AFTER CREATE');});
test('Midnight form submission uses the new local production day',async()=>{const h=appHarness([order()]);h.run("today=()=> '2026-09-30';reprintModal(['NT-TEST']);today=()=> '2026-10-01'");await h.e('reprintForm').onsubmit({preventDefault(){}});assert.equal(h.getState().pending[0].operation.productionDate,'2026-10-01');assert.equal(h.e('dateFilter').value,'2026-10-01');});
test('Archive and restore preserve production day, original date and print cycle',()=>{const b=backend(),old=b.seed(),r=b.mutate(b.reprint(old)).order,ready=b.mutate({...upsert(r),data:{...C.fields(r),currentStep:7}}).order,a=b.mutate({kind:'archive',id:r.id,opId:C.uid(),expectedRevision:ready.revision}).archive;assert.equal(a.productionDate,r.productionDate);assert.equal(a.createdAt,old.createdAt);assert.equal(a.printCycleId,r.printCycleId);assert.equal(C.productionDay(a),'2026-09-30');const restored=b.mutate({kind:'restore',id:r.id,opId:C.uid(),expectedRevision:a.revision},'admin').order;assert.equal(restored.productionDate,r.productionDate);assert.equal(restored.printCycleId,r.printCycleId);});
test('Legacy v13.5 archive recovers production metadata from its matching recycle snapshot',()=>{const b=backend(),r=b.mutate(b.reprint(b.seed())).order,ready=b.mutate({...upsert(r),data:{...C.fields(r),currentStep:7}}).order;b.mutate({kind:'archive',id:r.id,opId:C.uid(),expectedRevision:ready.revision});b.archives.data[1]=b.archives.data[1].slice(0,14);const a=b.ctx.nfSnapshot_('operator').archives[0];assert.equal(a.productionDate,r.productionDate);assert.equal(a.printCycleId,r.printCycleId);});
test('New schema columns reject collisions in active R and archive O/P',()=>{for(const [name,index] of [['Antrean Produksi',17],['Arsip Produksi',14],['Arsip Produksi',15]]){const b=backend(),table=b.tables.get(name);table.data[0][index]='CUSTOM KEEP';assert.throws(()=>b.ctx.nfSnapshot_('operator'),e=>e.code==='SCHEMA_CONFLICT');assert.equal(table.data[0][index],'CUSTOM KEEP');}});
test('Restoring legacy print moves reconstructs receipts and protects a new cycle',()=>{const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const original=s.pending[0].operation,newId=C.uid();P.relinkOperation(s,original.opId,newId);const op={...original,opId:newId};delete op.printJobId;delete op.printSignature;s.pending=[{operation:op,status:'blocked'}];const saved={...j,moves:P.exportMoves(j,s)},main=state([{...o,printCount:2,printCycleId:'PC-NEXT'}]),prints={};P.restoreBackup(main,prints,{pending:s.pending,print:{jobs:[saved]}},true);assert.equal(main.printReceipts[newId].jobId,j.id);assert.equal(main.pending[0].operation.opId,newId);assert.throws(()=>P.rebaseData(main,op,main.snapshot.orders[0]),/nomor cetakan/);});
test('Cycle guard still blocks backup rebase when all print receipts are missing',()=>{const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const op=s.pending[0].operation;delete op.printJobId;delete op.printSignature;assert.throws(()=>P.rebaseData(state([o]),op,{...o,printCount:2}),/nomor cetakan/);});
test('Print-only backups restore links without adding operations to the save queue',()=>{const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const op=s.pending[0].operation,main=state([o]),prints={};P.restoreBackup(main,prints,{format:'nametagflow-print-v1',jobs:[{...j,moves:P.exportMoves(j,s)}]},false);assert.equal(main.pending.length,0);assert.equal(main.printReceipts[op.opId].jobId,j.id);assert.match(P.jobStatus(prints.printJobs[0],main),/Periksa/);P.restoreBackup(main,prints,{pending:s.pending,print:{jobs:[j]}},true);assert.equal(main.pending.length,1);assert.match(P.jobStatus(prints.printJobs[0],main),/menunggu/);});
test('Restoring backup twice preserves operation IDs and later local acknowledgments',()=>{const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const backup={pending:clone(s.pending),print:{jobs:[clone(j)],receipts:clone(s.printReceipts)}},main=state([o]),prints={};P.restoreBackup(main,prints,backup,true);P.restoreBackup(main,prints,backup,true);assert.equal(main.pending.length,1);const op=main.pending[0].operation;C.applyAcknowledgment(main,op,ack(op,{...o,...op.data}));P.restoreBackup(main,prints,backup,false);assert.equal(main.printReceipts[op.opId].confirmed,true);assert.equal(P.jobStatus(prints.printJobs[0],main),'Cetak dikonfirmasi');});
test('Logo keys distinguish spacing and separate unnamed logos by order',()=>{assert.notEqual(P.logoKey({...order(),logo:'AB'}),P.logoKey({...order(),logo:'A B'}));assert.notEqual(P.logoKey(order('NT-A')),P.logoKey(order('NT-B')));});
test('PNG and JPEG logos retain aspect ratio, fit the tag and embed in PDFs',async()=>{for(const file of ['logo-demo.png','logo-wide.jpg']){const logo=fixtureLogo(file);assert.equal(P.logoImageInfo(logo).width,logo.width);const rows=[2,3,4,7,8,9].map(i=>({...order('NT-'+i),model:models[i],logo:'DEMO'})),assets={[P.logoKey(rows[0])]:logo},job=P.createJob(rows,{},assets);for(const o of rows){const image=P.artwork(o,{},assets).shapes.find(s=>s.type==='image');assert(Math.abs(image.w/image.h-logo.width/logo.height)<.0001);assert(image.x>=0&&image.x+image.w<=80.4);assert(image.y>=0&&image.y+image.h<=20.4);}const bytes=await P.pdf(job),doc=await PDFLib.PDFDocument.load(bytes);assert.equal(doc.getPageCount(),1);assert(!Buffer.from(bytes).includes(Buffer.from('/ObjStm')));}});
test('Low-resolution and falsified logo dimensions block production',()=>{const o={...order(),model:models[2],logo:'DEMO'};assert.throws(()=>P.createJob([o],{}, {[P.logoKey(o)]:fixtureLogo('logo-lowres.png')}),/150 dpi/);assert.throws(()=>P.createJob([o],{}, {[P.logoKey(o)]:{...fixtureLogo(),width:999}}),/Ukuran/);assert.throws(()=>P.logoImageInfo({data:'data:image/png;base64,ZmFrZQ==',width:300,height:300}),/Ukuran/);});
test('Transparent or invisible dark upload is rejected; white/color pixels accepted',()=>{assert.throws(()=>P.checkLogoPixels(new Uint8ClampedArray([255,255,255,0])),/transparan/);assert.throws(()=>P.checkLogoPixels(new Uint8ClampedArray([0,0,0,255])),/gelap/);P.checkLogoPixels(new Uint8ClampedArray([255,255,255,255]));});
test('Legacy jobs keep their embedded logo despite the new cache keys',async()=>{const o={...order(),model:models[2],logo:'A B'},legacy={id:'CT-LEGACY',engine:'13.5.0',createdAt:order().createdAt,orders:[o],settings:P.settings(),assets:{AB:fixtureLogo()}};assert(P.jobAssets(legacy)[P.logoKey(o)]);assert.equal((await PDFLib.PDFDocument.load(await P.pdf(legacy))).getPageCount(),1);});

function fakeDatabase(records,failSecondPut=false){return{transaction(){let remaining=0,aborted=false,puts=0;const staged=new Map([...records].map(([k,v])=>[k,clone(v)])),tx={abort(){aborted=true;queueMicrotask(()=>tx.onabort?.());},objectStore(){return{get(key){remaining++;const req={};queueMicrotask(()=>{req.result=clone(staged.get(key));req.onsuccess?.();if(--remaining===0&&!aborted)queueMicrotask(()=>{if(aborted)return;records.clear();for(const [k,v] of staged)records.set(k,clone(v));tx.oncomplete?.();});});return req;},put(value,key){if(failSecondPut&&++puts===2)throw new Error('TEST_QUOTA');staged.set(key,clone(value));}};}};return tx;}};}
test('Actual app restores main queue and print records in one transaction, including rollback',async()=>{for(const fail of [false,true]){const {o,j,s}=printing();P.finishJob(s,j.id,'Test');const h=appHarness([o]),ep=h.run('endpoint'),records=new Map([[ep,state([o])],[ep+'::print',{}]]);h.ctx.database=fakeDatabase(records,fail);h.ctx.backup={endpoint:ep,pending:s.pending,print:{jobs:[j],receipts:s.printReceipts}};h.run('db=database');if(fail){await assert.rejects(h.run('restoreWorkspace(backup,true)'),/TEST_QUOTA/);assert.equal(records.get(ep).pending.length,0);assert.equal(records.get(ep+'::print').printJobs,undefined);}else{await h.run('restoreWorkspace(backup,true)');assert.equal(records.get(ep).pending.length,1);assert.equal(records.get(ep+'::print').printJobs.length,1);assert.equal(records.get(ep).printReceipts[s.pending[0].operation.opId].jobId,j.id);}}});
function printUIHarness(rows,assets){const elements=new Map(),uploads=[],omits=[];let modalHTML='',saved=null;const s={...state(rows),printAssets:clone(assets)};s.snapshot.capabilities={printCycle:true};function element(id){if(!elements.has(id))elements.set(id,{id,value:'',checked:false,disabled:false,classList:{add(){}},dataset:{},innerHTML:'',textContent:''});return elements.get(id);}const body=element('modalBody');body.querySelectorAll=selector=>selector==='[data-logo-upload]'?uploads:selector==='[data-logo-omit]'?omits:[];body.querySelector=selector=>omits[Number(selector.match(/"(\d+)"/)[1])];const ctx=vm.createContext({NFCore:C,NFPrint:{...P,pdf:async()=>new Uint8Array([1])},document:{getElementById:id=>elements.get(id)||null,createElement:()=>({click(){},remove(){}}),body:{append(){}}},URL:{createObjectURL:()=>'',revokeObjectURL(){}},Blob,setTimeout:()=>0,confirm:()=>true,Date,Map,Set,console});const adapter={state:()=>s,context:()=> 'test',endpoint:()=> 'test',operator:()=> 'test',toast(){},dirty(){},isDirty:()=>false,save:async fn=>{fn(s);saved=s.printJobs?.[0];},modal(title,html){modalHTML=html;for(const m of html.matchAll(/\bid="([^"]+)"([^>]*)/g)){const el=element(m[1]),value=m[2].match(/value="([^"]+)"/);if(value)el.value=value[1];el.checked=/\bchecked\b/.test(m[2]);}element('modal');for(const m of html.matchAll(/data-logo-upload="(\d+)"/g))uploads[+m[1]]={dataset:{logoUpload:m[1]},files:[]};for(const m of html.matchAll(/data-logo-omit="(\d+)"/g))omits[+m[1]]={dataset:{logoOmit:m[1]},checked:false};}};vm.runInContext(fs.readFileSync(root+'/print-ui.js','utf8'),ctx);element('printSelected');element('printJobsBtn');ctx.NFPrintUI.init(adapter);return{ctx,s,uploads,omits,e:element,open:()=>ctx.NFPrintUI.openBuilder(rows),saved:()=>saved,html:()=>modalHTML};}
test('Actual print builder does not carry an omitted logo into a new sheet',async()=>{const o={...order(),model:models[2],logo:'DEMO'},h=printUIHarness([o],{[P.logoKey(o)]:{omit:true}});h.open();h.e('pcReviewed').checked=true;await h.e('pcExport').onclick();assert.match(h.e('pcError').textContent,/belum diunggah/);assert.equal(h.saved(),null);});
test('Failed logo replacement clears old asset and keeps export disabled',async()=>{const o={...order(),model:models[2],logo:'DEMO'},h=printUIHarness([o],{[P.logoKey(o)]:fixtureLogo()});h.open();h.uploads[0].files=[{type:'image/gif',size:123}];await h.uploads[0].onchange();assert.equal(h.e('pcExport').disabled,true);assert.match(h.e('pcError').textContent,/PNG atau JPG/);h.e('pcReviewed').checked=true;await h.e('pcExport').onclick();assert.equal(h.saved(),null);});

test('Recovery refuses a legacy journal plan that rolls back print count',()=>{const b=backend(),o=b.seed({...order(),printCount:2}),op=upsert(o),before=clone(b.active.data[1]),after=clone(before);after[9]=1;const plan={opId:op.opId,id:op.id,kind:'upsert',actor:'Test',time:order().createdAt,before,after};b.tables.get('_NF_Operations').data.push([op.opId,b.ctx.nfDigest_(op),'PENDING',JSON.stringify(plan),'',new Date(),'Test']);assert.throws(()=>b.mutate(op),e=>e.code==='PRINT_CYCLE_CHANGED');assert.equal(b.active.data[1][9],2);});

(async()=>{let passed=0;for(const [name,fn] of cases){try{await fn();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name+'\n'+e.stack);process.exitCode=1;}}console.log(`${passed}/${cases.length} tests passed. No network or live data used.`);})();
